Feat: add route table and route table routes
Azure/terraform-azurerm-avm-ptn-virtualwan pull request #131
Opened 2024-12-12 14:27 UTC by MinHeinA

## Description

adds route table and route table routes for the hubs created using this pattern module.

Closes #119 

-->

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [x] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [x] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [x] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

2024-12-18 11:24 UTC, jtracey93 requested changes

2024-12-18 11:24 UTC, jtracey93 commented on examples/vhub-routes/sudo apt update && sudo apt install terraform
Can this be removed please @MinHeinA

2024-12-18 12:29 UTC, MinHeinA commented on examples/vhub-routes/sudo apt update && sudo apt install terraform
Fixed

2025-08-13 19:16 UTC, trapeznikov commented
@jtracey93 any reason this hasn't been merged yet?

2025-09-15 00:00 UTC, khushal08 approved these changes
LGTM

2025-09-15 00:00 UTC, merged