Feature Enhancement - Github Issue: Clarify usage for key reference
Azure/terraform-azurerm-avm-ptn-virtualwan pull request #16
Opened 2024-01-12 05:12 UTC by khushal08

"Feature Enhancement - Github Issue: Clarify usage for key reference vs actual name of the resource"
Details Here - https://github.com/Azure/terraform-azurerm-avm-ptn-virtualwan/issues/9

2024-01-12 07:27 UTC, jtracey93 approved these changes
LGTM

2024-01-12 10:08 UTC, jaredfholgate requested changes
The code changes look good, but it looks like the docs have not been updated?

Your repo is missing all the standard AVM workflows that would check for this. They need to be added. You can use grept or I can help you.

It might be worth expanding on the docs in here also: https://github.com/Azure/terraform-azurerm-avm-ptn-virtualwan/blob/main/_header.md

Perhaps explain the usage in a bit more detail for people unfamiliar with virtual wan and this module?

2024-01-12 10:13 UTC, matt-FFFFFF reviewed
Some recommended changes

2024-01-12 10:13 UTC, matt-FFFFFF commented on firewall.tf
> +    virtual_hub_id = azurerm_virtual_hub.virtual_hub[each.value.virtual_hub_map_key].id
Can we call this _resource_id instead of just _id?

2024-01-12 10:13 UTC, matt-FFFFFF commented on p2s-vpn-gateway.tf
> +  virtual_hub_id              = azurerm_virtual_hub.virtual_hub[each.value.virtual_hub_map_key].id
Same here.. use _resource_id

2024-01-29 09:49 UTC, jaredfholgate commented
@khushal08 I think this PR can be closed now as I updated the naming for all the key vs name variables I could find in #23. So this one is already taken care of.

2024-04-19 07:34 UTC, closed without merging